### ISSUE TITLE
executable Paybox (CGI)

### ISSUE THREAD

**Issue by Struktur** [swoelffel/woocommerce-paybox-gateway#1]
Je me permet de m'exprimer en Français... la majorité des utilisateurs de Paybox semblent français...

Tout d'abord merci pour ton travail !

J'ai cependant un petit souci avec l'URL du CGI. Je m'explique ; j'ai bien placé mon CGI où il faut, lui ai attribué les droits necessaires, et j'ai fait quelques tests avec le module fourni par la banque : ça fonctionne.

Ensuite j'ai installé ton plugin, tout semble ok :)
Premier test, et malheureusement j'ai un message m'indiquant que le module Paybox n'a pas été trouvé. L'url est pourtant la "bonne". 
Est-ce que le problème pourrait venir d'ailleurs ?

Merci d'avance !

**Comment by swoelffel** [comment]
Bonjour,

Tu dois avoir le message "Paybox CGI module can not be found" : c'est bien ca ?
Si c'est le cas, cela signifie que le chemin ves le CGI (Complete path to PayBox CGI) n'est pas le bon.

En effet, il doit s'agir d'un chemin physique (vérifié par un "file_exist" sur le serveur) et non d'une URL.
C'est trompeur car nous utilisons la CGI comme un EXE et non comme une CGI en fait.

Attention, il faut aussi que ton utilisateur apache ai les droits ad hoc pour exécuter la CGI (shell_exec) ... Sinon tu auras un autre message d'erreur "Permissions are not correctly set for file ...".

Je suis preneur de tout retour sur le fonctionnement du plug-in, merci

Bonne continuation,

Stéphane

**Comment by Struktur** [comment]
Salut Stéphane, 

Merci pour ton aide, je n'avais pas percuté qu'un CGI avait besoins du chemin physique... merci !
Je vais y remédier ;)

Je suis très content d'avoir trouvé ton plut-in et je ne manquerai pas de te faire des retours dès que je l'aurai correctement configuré.

**Comment by Struktur** [comment]
Une question ! Le chemin se fait par rapport à quel répertoire ? Est-ce que je dois prendre le répertoire /plugins/ ou la racine de mon site comme "point de départ" ?

**Comment by swoelffel** [comment]
Idéalement la racine du serveur ... il n'est pas nécessaire que l'exe Paybox soit dans l'arborescence du site du moment qu'Apache le "voit" et peut l’exécuter.
T'es sur Win ou Linux ?

**Comment by Struktur** [comment]
Je suis sous linux, sous ubunu (10.04 LTS). 

Le CGI est dans un répertoire cgi-bin, à côté de mon répertoire htdocs.
- HTDOCS / racine du site
- CGI-BIN / module.cgi

Je peux lancer le CGI en tapant l'adresse du site/cgi-bin/module.cgi ;

**Comment by swoelffel** [comment]
Tu peux déjà le lancer en ligne de commande pour s'assurer qu'il a les bon droits (7xx)
Je pense que ça devrait plutôt être un truc du genre /var/www/cgi-bin/module.cgi

**Comment by Struktur** [comment]
Merci Stéphane,

Je suis entré en contact avec mon hébergeur pour avoir connaissance du chemin physique à renseigner.
Je te tiens au courant de la suite ;)

**Comment by Struktur** [comment]
Le problème est résolu. Petite explication pour ceux qui seraient dans la même situation que moi (Ubuntu 10.04) le chemin vers mon répertoire CGI doit suivre ce schémas : /srv/d_votre_disk/www/www.siteweb.tld/cgi-bin/nom_du_fichier

il faut donc renommer d_votre_disk par le nom de votre disque, et www.siteweb.tld par le virtualhost.
