### ISSUE TITLE
Question sur Paybox return URL

### ISSUE THREAD

**Issue by gueurk** [swoelffel/woocommerce-paybox-gateway#10]
Bonjour,

Petite question sur ce champs. 
Je l'ai défini, mais je sais pas trop comment ça marche. 

Lorsque j'essaye d'accéder sur mon site à cette adresse je tombe sur une erreur 404 et en mode test, lorsque je la transaction est réussie coté paybox (ou refusée), le statut de ma commande n'est pas updaté. 

J'ai du louper quelque chose ... Que faire ? 

Merci d'avance,

**Comment by swoelffel** [comment]
Bonsoir,
Il s'agit juste d'un URL qui est "catchée" dans le init de wordpress. 
Si elle reçoit les bons paramètres, elle active l'auto-response.
En théorie, il suffit de laisser la valeur par defaut.
Possible d'avoir l'url du site pour verifier ?
Bonne soirée
