### ISSUE TITLE
Tests en local et exécutable CGI ?

### ISSUE THREAD

**Issue by Zealotux** [swoelffel/woocommerce-paybox-gateway#11]
Bonjour,

Tout d'abord : merci de mettre à disposition ce module fort utile à l'intégration de Paybox.

Ensuite, pardonnez mon manque de compétence dans ce système : c'est la première fois que j'intègre Paybox, et malgré le manuel d'intégration j'ai un peu de mal à paramétrer le système de test sur mon site.

Je développe donc le site avec un Wordpress local (via xampp sous Windows), j'ai indiqué le chemin vers mon CGI mais quand j'essaye de payer via PB, Windows m'ouvre le fichier :

![win](https://f.cloud.github.com/assets/5838360/1459299/aee1d576-43cd-11e3-8a7d-aef5b4659442.jpg)

Est-ce donc une erreur de ma part ou est-ce impossible de faire des tests en local ?

Merci d'avance et bonne journée !

**Comment by swoelffel** [comment]
Bonjour,
Je ne suis pas un grand expert Windows et n'ai pas moyen de tester mais peut être que renommer la CGI en .exe peut suffire ?
Manifestement, l'ami Windows n'a pas compris qu'il s'agissait d'un executable ...
Sinon, nous avons une offre SAAS pour la mise en oeuvre de boutique WooCommerce (incluant mes plugins paybox, socolissimo et bien d'autres) sur laquelle nous gérons les aspects techniques et infra : www.openboutique.fr
Si tu ne veux pas "t'embêter" avec la technique, n'hésites pas à nous solliciter :-)
Bonne journée

**Comment by Zealotux** [comment]
Bonjour,

Merci de ta réponse. Je pense faire mes tests sur un serveur linux parce le local sous Windows semble présenter quelques… limites. Je note l'offre SAAS dans un coin en tout cas merci !

Bonne journée

**Comment by swoelffel** [comment]
Pas de problème : je clos le ticket.
Bons tests ...
