### ISSUE TITLE
configuration des urls de retour

### ISSUE THREAD

**Issue by cristelle** [swoelffel/woocommerce-paybox-gateway#12]
Bonjour,
Je n'arrive pas à configurer correctement les urls de retour (j'ai une erreur 404).
quel chemin doit-on indiquer ?
(par ailleurs, bien qu'indiquant la plate forme de test preprod, je suis redirigée vers la plate forme de production https://tpeweb.paybox.com .. tous les autres paramètres que j'ai indiqués - textes, chemin du cgi- , sont correctement pris en compte)
voici ma config (c'est un site de test)
Home URL:   http://eip.nkdn.fr/woo/wordpress
Site URL:   http://eip.nkdn.fr/woo/wordpress
WC Version:     2.0.19
WC Database Version:    2.0.19
WP Version:     WP 3.7.1
Web Server Info:    Apache/2.2.22 (Debian)

Merci !

**Comment by swoelffel** [comment]
Bonjour,

Il y'a effectivement un problème avec les paramètres de tests.
Une nouvelle version corrigeant ce problème est en cours de test et devrait être livrée courant de semaine prochaine.
Elle intégrera également un outil pour créer automatiquement les pages de retour (transaction annulée par l'internaute et transaction refusée).
Je vous tiens au courant.

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1556213/1464a888-4eb9-11e3-82c5-2d7ca0802380.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
ok, merci beaucoup.

Cristelle Barillon.

**Comment by swoelffel** [comment]
Bonsoir,
La nouvelle version intégrant plusieurs améliorations vient d'être poussée sur GitHub.
J'attends votre retour pour clôre le ticket et mettre à jour le plugin sur wordpress.com
Merci
Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1566591/6c797a10-5091-11e3-879f-fd35bab85864.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
Merci.
Pour l'instant j'ai une erreur immédiate car mon site n'est pour l'instant
pas installé directement sous la racine . Je suis en phase de test là :
http://eip.nkdn.fr/woo/wordpress/ pour le moment.. et donc le wp-admin se
trouve chez moi après le chemin woo/wordpress , ce qu'il faudrait que je
puisse renseigner quelque part.
merci à nouveau.

Cristelle Barillon.

**Comment by swoelffel** [comment]
Ok, je clôture le ticket.
N'hésitez pas à revenir vers moi en cas de difficulté.
Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1574795/e0490872-5143-11e3-8acf-f70f2136d1a3.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
Je ne comprends pas, je vous dis que la configuration des urls de retour
échoue immédiatement ?
Je rentre en dur dans le code alors ?

2013/11/19 Stéphane notifications@github.com

**Comment by swoelffel** [comment]
Désolé, je n'ai pas compris votre dernier message.
Qu'entendez vous par "échoue immédiatement" ?
Si vous avez installé la dernière version 0.3.2, vous devez avoir un nouveau bouton permettant d'envoyer vos paramètres au support.
Merci de cliquer sur ce bouton svp.
Une copie d'écran de l'interface de paramétrage du plugin serait utile.
Merci
Stéphane W
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1575696/70d66134-5151-11e3-9e0c-4dabc0d22e85.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
si je fais "install return pages" j'ai :
"The requested URL /wp-admin/admin.php was not found on this server."

ce qui est normal puisque mon wordpress/woocommerce est situé dans un sous
répertoire.

Quels sont les paramètres qui sont transmis par le "send report" ?

2013/11/19 Stéphane notifications@github.com

**Comment by swoelffel** [comment]
Je viens de pousser une nouvelle version pour résoudre ce pb.
Le send report envoi le contenu du formulaire de paramétrage du plugin.

Stéphane W
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1576598/1864c406-515f-11e3-9553-40675fd89f4e.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
je viens d'envoyer un report.
- les urls de retour aboutissent encore sur une erreur 404
- je n'arrive pas non plus à accéder à l'auto-response.

sinon la connection au site de paybox se fait correctement, les "Paybox
return pages" sont correctement installées apparemment.

Cristelle B.

**Comment by swoelffel** [comment]
Bien reçu
Je regarde et reviens vers vous.
Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1577089/1c41470a-5166-11e3-82b1-ed66c56b92e1.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
merci !

**Comment by swoelffel** [comment]
Pouvez-vous activer le mod-rewrite apache ?
Les pages sont bien présentes mais à ces urls ::
Canceled -> http://eip.nkdn.fr/woo/wordpress/?page_id=57
et
Refused -> http://eip.nkdn.fr/woo/wordpress/?page_id=56
pour l'autoresponse, je pense qu'un "post" vide pourrait faire l'affaire.
Sinon, le plus simple est d'activer le mod-rewrite (ce qui sera de toute façon utile pour votre référencement)

PS : Si vous ne voulez pas perdre de temps sur la config technique, vous pouvez vous faire heberger chez nous : http:www.openboutique.fr ... ;-)

**Comment by cristelle** [comment]
le mod-rewrite est activé (et l'a toujours été)...

j'ai vu en effet que les pages ont correctement été crées, mais comment
faire pour que la redirection depuis checkout/ marche ? est-ce qu'il faut
que je le mette en dur quelque part ?
En fait, même directement, je ne sais pas sur quelle adresse accéder aux
pages de  'checkout', par exemple,
http://eip.nkdn.fr/woo/wordpress/checkout/canceled est en 404.

pour la page d'autoresponse, idem, il faut une redirection sur un post vide
?

merci,
Cristelle.

**Comment by swoelffel** [comment]
OK mais il ne semble pas pris en compte car c'est Apache qui renvoi le 404.
Vous avez quoi dans le .htaccess à la racine de votre WP ?
Vous avez bien AllowOverride à true dans la conf Apache ? 

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1581212/f39f833c-51d0-11e3-853e-221847ba2267.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
je n'ai pas de .htaccess dans la racine du wp !! ai-je zappé un truc à ce
niveau-là ? y a-t-il des rewrite à installer quelque part ?
(AllowOverride est true)

**Comment by swoelffel** [comment]
Oui dans le .htaccess de la racine de WP pour les permalinks qui sont une best practice WP (http://codex.wordpress.org/Using_Permalinks)

![capture decran 2013-11-20 a 20 28 29](https://f.cloud.github.com/assets/3170667/1585317/fdc3ffc0-5219-11e3-917c-65e65a3c9692.png)

On peut faire sans, mais dans ce cas, il ne faut pas non plus les utiliser dans le plugin.
Je clôture le ticket car il me semble que le pb ne vient pas du plugin.

Revenez vers moi si le pb persiste.

Bonne soirée,

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1585304/e0aa4980-5219-11e3-8b77-58db297268df.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
Bonjour,
La présence du .htaccess semble effectivement améliorer les choses.. mais
les urls de retour canceled et refused sont maintenant redirigées vers la
page d'accueil du wordpress... est-ce que je dois explicitement écrire les
rewrite de ces urls dans le .htaccess ?
Merci,
Cristelle.

2013/11/20 Stéphane notifications@github.com

**Comment by swoelffel** [comment]
Bonjour,
Non non : Il faut juste créer les pages ... Le bouton doit s'en charger en théorie.
Vous ne les voyez pas dans le Backend (menu pages) ?
Si vous ne trouver pas, passez en 0.3.3 et renvoyez moi les paramètres svp, j'ai ajouté l'ID des 2 posts et l'url du WP dans les données envoyées (en plus du contenu du formulaire).

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1606747/70e18cfa-5456-11e3-8b4d-bb7170d67b45.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
Bonjour,
Je viens de vous faire un send report.
Le problème persiste : le retour de paybox, refused/cancelled/success aucun
ne marche : ils aboutissent tous sur la page d'accueil du site et la db des
commandes n'est pas mise à jour en cas de succès.
Les pages de retour existent bien et fonctionnent correctement avec par
exemple le paiement "cheque".
Via votre interface, les pages refused/cancelled sont données comme
installées (ce qui vrai puisqu'elles fonctionnent avec les autres moyens de
paiement), mais le lien qui est supposé les vérifier ne sont pas corrects
(n'adressent pas le sous-repertoire où mon wordpress est installé)

Cristelle.

**Comment by swoelffel** [comment]
Bonjour,

j'ai reçu les paramètres suivants :
    [woocommerce_paybox_return_url] => woo/wordpress/paybox_autoresponse
    [woocommerce_paybox_callback_success_url] => woo/wordpress/checkout/order-received/
    [woocommerce_paybox_callback_refused_url] => woo/wordpress/checkout/order-refused/
    [woocommerce_paybox_callback_cancel_url] => woo/wordpress/checkout/order-canceled/

Pourriez-vous essayer avec un "/" en début de chaine.

Pour le premier par ex : 
/woo/wordpress/paybox_autoresponse

Pour vérifier que cela fonctionne, vous devez avoir ca :
http://demo3.openboutique.fr/paybox_autoresponse?order&sign

donc pour votre site :
http://eip.nkdn.fr/woo/wordpress/paybox_autoresponse?order&sign

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1632710/4491adbe-577c-11e3-858c-6dfd34e41656.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
non ça ne change rien, quoi que je fasse, y compris le test d'autoresponse,
je suis toujours redirigée vers la page d'accueil du wordpress.

**Comment by cristelle** [comment]
(ha non pardon, le test d'autoresponse marche maintenant)

**Comment by swoelffel** [comment]
Ah bonne nouvelle !!
Pour les autre URLs, comme vous n'avez pas activé les permaliens (vous devriez), il faut prendre les URLs existantes (voir le menu checkout)
Par ex : /woo/wordpress/?page_id=20 pour order received

Dites-moi si je peux clotuter le ticket svp ?

Merci

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1632832/4700789e-577e-11e3-9822-81965f729cbe.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
bon il semble que ça marche !!

juste une dernière chose, quand la commande est validée, j'ai juste une
page de retour du genre laconique, order received, merci, votre commande a
bien été reçue (et la commande est bien enregistrée, indiquée en
processing).
Voilà l'url de retour :
http://eip.nkdn.fr/woo/wordpress/checkout/order-received/?order=75&erreur=00000&carte=CB&numauto=XXXXXX&numtrans=3877530&numabo=0&montantbanque=1900&sign=gPDlqZrAwUDy3zxq69HkDIahSOpA%2FmesZscqQI%2BY29fPxnV5y5CWPRjOY0NtxKcfs3oaxLVb4aw6y91BSJnOhYXb3YGGjeuC9JEHT9rdYm3jBJz%2Fz%2BthackqqUhSSnduWgoVyIm%2BJDNklfwTA4j1XPkTO9C4ep8F%2BgbuOODB5TM%3D

Si j'effectue le "paiement par chèque", la page order received reprend,
elle, toutes les données de la commande (numéro, date, total, etc.. détails
du client) ce qui est plus rassurant pour le client.
[ Voilà l'url de retour
http://eip.nkdn.fr/woo/wordpress/checkout/order-received/?order=74&key=order_529621e61063e]

Est-ce que cette différence est normale ?

Merci
Cristelle.

**Comment by swoelffel** [comment]
Il faut dans ce cas utiliser le shortcode qui va bien [openboutique_thankyou] en lieu et place du shortcode woocommerce [woocommerce_thankyou].
Ca marche même sur les commandes passées.

J'effectuerai le remplacement en automatique avec le bouton d'installation des pages dans la prochaine version.
Je clôture le ticket ...

N'hésitez pas à mettre une petite étoile dans le "star" de github et sur http://wordpress.org/plugins/woocommerce-paybox-gateway/ si vous trouvez le plugin utile ... :-) Merci

Bonne continuation,

Stéphane
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1633623/5d0c0fd2-578c-11e3-95a2-22bd6302b557.png)
http://www.openboutique.fr

**Comment by cristelle** [comment]
super ! merci beaucoup ça marche très bien.
oui je trouve le plugin tout à fait utile, je vais pouvoir basculer notre
boutique actuelle (un vieux zencart qui a mal supporté une tentative de
migration) sur woocommerce. La paybox était la condition sine qua non car
seule solution acceptée par notre banque.
merci encore, à bientôt.
Cristelle.

**Comment by mikaouel** [comment]
Bonjour, 

J'ai également un problème avec /paybox_autoresponse, j'ai une erreur 404: 

WARNING: Impossible de joindre http://www.biocontrol2014.com/paybox_autoresponse pour le paiement order=464&erreur=....

Dans le module paybox, pour Paybox return URL, j'ai laissé /paybox_autoresponse, je dois mettre autrechose?

Pour les autres URL tout est OK.

Merci d'avance.

Mika

**Comment by swoelffel** [comment]
Bonjour,
Je pense que vous n'avez pas activé le rewrite (voir le thread ci-dessus)
Cordialement
Stéphane
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1633623/5d0c0fd2-578c-11e3-95a2-22bd6302b557.png)
http://www.openboutique.fr

**Comment by mikaouel** [comment]
Bonjour, merci pour votre rapidité (je n'ai pas accès au.htaccess) , j'ai demandé à l'hébergeur de faire le nécessaire et je reviens vers vous.
