### ISSUE TITLE
Nouveau code d'erreur PAYBOX

### ISSUE THREAD

**Issue by CharlesS** [swoelffel/woocommerce-paybox-gateway#14]
Bonjour,

Un nouveau code d'erreur a été implémenté sur PAYBOX (00040). 

La doc est a cette adresse : http://www1.paybox.com/telechargements/ManuelIntegrationPayboxDirect_V6.1_FR.pdf

Cela s'est manifesté par un code d'erreur retour inconnu de mon coté.
En espérant que cela soit utile.

**Comment by swoelffel** [comment]
Bonjour Charles,

Merci pour l'info : je prépare une version 0.3.5 intégrant ce nouveau code erreur dans la semaine.

Bonne journée

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1671449/12964ad4-5cba-11e3-8095-5f4d0a161156.png)
http://www.openboutique.fr

**Comment by swoelffel** [comment]
Bonsoir,

Nouvelle version poussée ce soir avec mise à jour de l'ensemble de la gestion d'erreur pour tenir compte de la dernière documentation. Le code 00040 correspond à un check 3-DSecure non réussi.
Attention, il s'agit de la version 6.1 de Paybox System (et non Direct) du 27/11/2013 également : http://www1.paybox.com/telechargements/ManuelIntegrationPayboxSystem_V6.1_FR.pdf

Bonne soirée,

Stéphane
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1677195/3b2eb18c-5d25-11e3-9155-996ca95f5391.png)
http://www.openboutique.fr
