### ISSUE TITLE
Permissions are not correctly set

### ISSUE THREAD

**Issue by Zealotux** [swoelffel/woocommerce-paybox-gateway#15]
Bonjour,

J'ai développé mon site sur un hébergement OVH (qui me sert pour mes développements) et sur ce dernier : le Paybox Gateway fonctionne à merveille en mode test.

Je travaille depuis aujourd'hui à l'intégration du site en question sur son hébergement final (lui aussi un OVH mutualisé) sur lequel j'ai effectué la même manipulation, c'est à dire : placer le fichier paybox.cgi à la racine (même répertoire que le /www/) avec les autorisations 755 puis donner le lien absolu aux paramètres du plugin mais lors du paiement j'ai une erreur :

"Permissions are not correctly set for file /homez.800/editionswd/paybox.cgi"

Ce que je ne comprends pas c'est que j'ai fait exactement la même chose que pour mon Wordpress de test (lien absolu, fichier paybox.cgi au même endroit avec les mêmes autorisations) mais dans ce cas le module ne semble pas avoir les bonnes autorisations pour s’exécuter.

Ai-je oublié quelque chose ? Merci d'avance et bonne journée.

**Comment by mikaouel** [comment]
Bonjour, 

J'ai exactement la même problème, sur NUXIT et woocommerce. ça fait 5 jours que je tourne et que je relis tous les forum possible, mais à priori il n'y aurai que celui-ci pour me sortir de là.

NUXIT propose nativement un cgi (modulev2.cgi de paybbox qui se trouve dans le PATH par défaut) les droits pour utiliser des executable est bien activé et j'ai toujours les mêmes messages d'erreur: 

Warning: shell_exec() has been disabled for security reasons in /web/biocontrol2014/www/wp-content/plugins/woocommerce-paybox-gateway-master/class-wc-paybox-gateway.php on line 316

Permissions are not correctly set for file /web/biocontrol2014

Nuxit m'indiqe également de mettre: shell_exec("modulev2.cgi") ce que j'ai fait sur la ligne 316 du PHP, mais rien n'y fait.

Auriez-vous le début d'une piste?

**Comment by swoelffel** [comment]
Bonjour,

Tout est dans le message d'erreur : Warning: shell_exec() has been disabled for security reasons

shell_exec est indispensable pour executer la CGI.

Une seule solution -> Changer d'hébergeur pour un qui autorise les shell_exec.

Bonne soirée

**Comment by swoelffel** [comment]
@Zealotux : probablement un pb similaire -> que dit le php_error.log ?

**Comment by Zealotux** [comment]
Merci pour cette réponse, malheureusement je suis sur un hébergement mutualisé chez OVH et je ne pense pas avoir accès à ce fichier.

En tout cas je suis presque sûr que le problème vient aussi de shell_exec() qui ne doit pas être autorisé sur les hébergements mutualisés. Je vais contacter le support OVH pour voir si celui-ci peut-être débloqué.

Merci pour ce support !

**Comment by mikaouel** [comment]
Merci beaucoup pour votre réactivité. Nuxit m'a également répondu à ce sujet (pour la solution paybox): 

pour intégrer votre module de paiement Vous devez utiliser le fichier modulev2 commun que nous mettons à votre disposition. Ce fichier se trouve dans le PATH par défaut, ce qui signifie que vous n'avez pas besoin d'en indiquer le chemin. Voici comment le charger :
shell_exec("modulev2.cgi"); 
Ou :
shell_exec("modulev2"); 

Maintenant comment je fait le lien entre votre plugin qui est très bien fait et leur consigne, quelle adresse dois-je mettre pour "Complete path to PayBox CGI"?

Vraiment merci encore!

**Comment by swoelffel** [comment]
@mikaouel : Dans ce cas, vous mettez juste modulev2.cgi sans chemin et cela va executer shell_exec("modulev2.cgi");

**Comment by swoelffel** [comment]
@Zealotux : C'est possible. 
Désolé mais sans les logs PHP, il est difficile d'être sur à 100%
Vous pouvez vous rapprocher de nous si vous chercher un hosting dédié WooCommerce avec les plugins en place.

Je clôture le ticket.
Bonne soirée

Stéphane
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1574795/e0490872-5143-11e3-8acf-f70f2136d1a3.png)
http://www.openboutique.fr

**Comment by mikaouel** [comment]
quelle galère, maintenant j'ai "Paybox CGI module can not be found"
Je leur ai demander de m'indiquer le chemin vers le cgi. Néanmoins je ne dois faire aucune modification sur le fichier class-wc-paybox-gateway?

vraiment merci.

**Comment by swoelffel** [comment]
@mikaouel : le "shell_exec("modulev2.cgi");" j'y crois pas trop.
Vous pouvez tenter de le faire dans un simple fichier php :
<?php
shell_exec("modulev2.cgi");
?>

et voir ce que cela donne ... 
Si cela ne marche pas -> voir avec votre hébergeur ...

Nous fournissons des hébergement dédié woocommerce si vous ne trouvez pas d'issue.

Bon courage

**Comment by mikaouel** [comment]
Bonjour, je viens de prendre contact de nouveau avec NUXIT, ils vont voir ce qui ne fonctionne pas sur leur fichier!
Je vous tiens au courant, merci encore!

**Comment by mikaouel** [comment]
Bonjour, 
Effectivement le modulev2 fonctionne avec cette directory: /home/bin/modulev2.cgi sur NUXIT, bon il a fallu tout de même plus de 25 post avec le service technique pour qu'il fonctionne! 
Merci en tout cas pour votre aide, si cette info peut servir à quelqu'un...

**Comment by Zealotux** [comment]
J'en profite pour poster le fin mot de l'histoire : j'ai téléchargé de nouveau l'exécutable sur le site de Paybox et maintenant il s'exécute. Incompréhensible pour moi, peut-être un problème de téléchargement qui a amené à une corruption du fichier.

En tout cas merci !
