### ISSUE TITLE
PAYBOX: WARNING

### ISSUE THREAD

**Issue by mousszy** [swoelffel/woocommerce-paybox-gateway#18]
Bonjour,

j'ai un problème après chaque paiement j'ai un mail avec ce message :  
WARNING: Impossible de joindre http://hype-shop.fr/paybox_autoresponse pour le paiement order=1321&erreur=00000&carte=Visa&numauto=292615&numtrans=218017974&numabo=0&montantbanque=1590&sign=fW%2BymCL7gutZKI8cWyKOF5MVorYOfAZmVRw%2FEbZHDVe9C%2FNzDvj9phQcdH%2FaO2gXOdE7oG%2BEngPnk6%2BjiEkFAPEWVOk4fUY3reBVKzADOkty%2FerKf8H3BO0fJP%2FldWf68jxdDs1LYU2AZ3Ys2OHwnAfoilbAaGRZwvWRCguzlo0%3D (404-0)

est la commande n'est pas valider du coup

**Comment by swoelffel** [comment]
Problème lié à un plug-in externe de sécurité, lequel ?

**Comment by mousszy** [comment]
non j'ai enlevé tous les plugins de sécurité
