### ISSUE TITLE
Fonctionnement URL de retour

### ISSUE THREAD

**Issue by Struktur** [swoelffel/woocommerce-paybox-gateway#2]
Bonjour,

Une petite question concernant l'url de retour du module.
J'ai deux URL à renseigner : "Return Link" et "Paybox return URL" Si l'une de ces URL est mal paramètrée, que se passe-t-il ? 

J'ai le cas d'un paiement qui semble passé mais qui est en attente dans Woocommerce. 
Je souhaite m'assurer que le paramètrage de cette url n'influe pas sur le paiement, mais simplement sur les messages clients.

**Comment by swoelffel** [comment]
Bonjour,

Nouvelle version postée pour résoudre le pb de compatiblité avec la v2 Woocommerce
Merci pour les tests,

A new version to allow compatibility with WooCommerce version 2 has been posted.

Stéphane
