### ISSUE TITLE
Install return page

### ISSUE THREAD

**Issue by pioum** [swoelffel/woocommerce-paybox-gateway#22]
Bonjour

Je teste le plugin. Pour l'instant ca fonctionne bien mais j'ai un message d'erreur quand je veux installer les pages de retour. Un probleme de permissions visiblement. Tu as une idée de ou ca pourrait venir?

merci pour ton aide

**Comment by sylwit** [comment]
La derniére PR corrige ce problème. Il faut modifier les paramètres de l'URL d'installation des pages

**Comment by pioum** [comment]
Merci. Cela fonctionne maintenant.
Au retour de paiement, j'ai la bonne page qui s'affiche avec le recap de la commande. Par contre le panier n'est pas vidé.

merci pour ton aide

**Comment by swoelffel** [comment]
Bonjour,
Est-ce que la bonne version du fichier shortcode_woocommerce_paybox_gateway.php est installée ?
En particulier la ligne 46:
unset( WC()->session->order_awaiting_payment );
Merci

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1581212/f39f833c-51d0-11e3-853e-221847ba2267.png)
http://www.openboutique.fr

**Comment by pioum** [comment]
oui. C'est la version 0.4.4.

**Comment by swoelffel** [comment]
Version 0.4.5 livrée -> doit régler le problème
J'attends votre retour pour clôturer le ticket et mettre à jour la version WP.

Merci

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1581212/f39f833c-51d0-11e3-853e-221847ba2267.png)
http://www.openboutique.fr

**Comment by pioum** [comment]
Ca fonctionne presque parfaitement ;-) En fait sur la page retour avec le récap de la commande passée, mon panier apparait toujours. Mais si je rafraichis la page ou si je vais sur une autre page, mon panier se vide. Après, le problème vient peut-être d'ailleurs...
en tout cas merci pour votre travail.

**Comment by swoelffel** [comment]
Y'a peut être un moyen de contourner -> Je regarde

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1581212/f39f833c-51d0-11e3-853e-221847ba2267.png)
http://www.openboutique.fr

**Comment by pioum** [comment]
J'ai de nouveau un souci : l'autoresponse ne fonctionne plus.

**Comment by swoelffel** [comment]
Bonjour,
Vous auriez plus de détail ?
Que donne l'appel de l'autoresponse dans un navigateur ?

**Comment by pioum** [comment]
Bonjour
L'auto response me donne : Test AutoResponse OK
Par contre je reçois un mail comme quoi l'auto response n'a pu être contacté.

**Comment by swoelffel** [comment]
Je pense que ce mail est envoyé par paybox, est ce bien le cas ?
Je vous invite à revoir vos paramètres Paybox dans ce cas.

**Comment by ludo29** [comment]
Bonjour j utilise Paybox actuellement tout fonctionne avec woocommerce sauf que lorsque je passe sur la visu des commande, la commande effectuée reste sur le statut "en attente" et du coup le marchand n'est pas automatiquement averti par email. Il faut passer la commande de façon manuelle au statut "en cours" et la le mail est expedié au marchand.

Comment la faire passer automatiquement alors que le paiement est effectué au statut "encours"?

D'avance merci

**Comment by swoelffel** [comment]
Bonjour,
Le statut est changé par l'autoresponse qui est appelé directement par les serveurs Paybox.
Il faut vérifier qu'il est accessible (page blanche avec le texte "Test AutoResponse OK")

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1581212/f39f833c-51d0-11e3-853e-221847ba2267.png)
http://www.openboutique.fr

**Comment by ludo29** [comment]
Bonjour merci pour votre réponse.

J'essaye cela dès que possible.
Par contre, comment vérifier qu'il est accessible? Une page a exécuté? un
parametre à specifier dans le plugin?

Grand merci.

**Comment by swoelffel** [comment]
Il faut appeler l'url : http://www.votresite.com/paybox_autoresponse (si vous ne l'avez pas modifiée)

**Comment by ludo29** [comment]
Merci beaucoup

**Comment by swoelffel** [comment]
Correction l'url serait  http://www.votresite.com/paybox_autoresponse?order&sign
Les deux paramètres en GET active l'autoresponse.

**Comment by ludo29** [comment]
Merci super sympa je vais rester

**Comment by ludo29** [comment]
Bonjour
J'ai une page nommée automatic_response sous la racine du site. Je spécifie cette page comme page d'auto reponse au niveau du plug in mais je n ai toujours pas automatiquement la validation de la commande.

Si vous aviez une idée?
merci

**Comment by swoelffel** [comment]
Bonjour,

Il ne faut pas créer de page pour la réponse automatique. Juste une URL dans les paramètres.
Je vais pousser une nouvelle version qui contiendra un lien pour vérifier que l'URL fonctionne.
Attention : Vous devez avoir activé le mode rewrite pour l'url par défaut.

Comme il ne s'agit pas d'un bug du plugin mais d'un besoin d'assistance, je vous invite à acheter un ticket de support sur notre site.

Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1581212/f39f833c-51d0-11e3-853e-221847ba2267.png)
http://www.openboutique.fr

**Comment by Tisseur2Toile** [comment]
Bonjour,

Je n'ai plus d'envoi de mails automatiques lors d'une validation de paiement par paybox, de plus, l'URL : http://www.votresite.com/paybox_autoresponse?order&sign
me retourne un 404.
Le site étant multilingue, j'ai essayé en incluant les chemins de langue mais rien n'y fait, je n'ai jamais accès à cette URL.
Aurais-je raté quelque chose lors de ma configuration ?
Merci d'avance pour votre réponse.

**Comment by swoelffel** [comment]
Bonjour,
Avez-vous vérifié le mod-rewrite : https://codex.wordpress.org/Using_Permalinks
Merci
