### ISSUE TITLE
WooCommerce::nocache() undefined

### ISSUE THREAD

**Issue by sylwit** [swoelffel/woocommerce-paybox-gateway#23]
Hi,

I've got this error on the order-pbx-received page

Fatal error: Call to undefined method WooCommerce::nocache() in /home/.../wp-content/plugins/woocommerce-paybox-gateway/shortcode_woocommerce_paybox_gateway.php on line 37

**Comment by swoelffel** [comment]
Hello,
Function is deprecated on WooCommerce. We are currently working on an update
Regards
Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1556213/1464a888-4eb9-11e3-82c5-2d7ca0802380.png)
http://www.openboutique.fr

**Comment by sylwit** [comment]
Thank you for your work.

Do you know when this new release will be published into wp repositories ?
