### ISSUE TITLE
woocommerce_paybox_check_response

### ISSUE THREAD

**Issue by sylwit** [swoelffel/woocommerce-paybox-gateway#26]
This function doesn't work if you have a "?" in your paybox autorespond URL.

If you disable permalink then you have to use a default pattern for your URL such as
 /?page=12345

Also why do you use a such complex syntax ?
$sign = substr($_SERVER['REQUEST_URI'], $pos_sign + 6);

Isn't it the same than 
$sign = $_REQUEST['sign'];

I started to tweak 
if (str_replace('//', '/', '/' . $return_url) == str_replace('//', '/', $my_WC_Paybox->return_url))

for 

if ( preg_math('#'.$my_WC_Paybox->return_url .'#', $_SERVER['REQUEST_URI']) ) which do almost the same without relying on the ? position

**Comment by swoelffel** [comment]
Bonjour,
Je vous confirme que le mod_rewrite doit être activé.
En pratique, nous avons "branché" le retour paybox sur le init de worpress pour pouvoir retourner une page sans aucun chargement parasite.
pour le $sign, nous avons choisi cette option au cas ou un "&" se trouve dans la chaine de retour.
Nous sommes preneur de toute solution qui vous semblerait adaptée.
Merci pour votre contribution
