### ISSUE TITLE
Paybox warning, erreur 404

### ISSUE THREAD

**Issue by matt-regnier** [swoelffel/woocommerce-paybox-gateway#27]
Bonjour, j'ai un problème d'erreur HTTP 404 entre le serveur PAYBOX et OVH.
En effet après paiement, mon serveur renvoie bien la page "Autoresponse". Tout semble fonctionner normalement mais Paybox m'envoie systématiquement un WARNING correspondant cette erreur :

-> 
WARNING: Impossible de joindre http://monsite.fr/paybox_autoresponse pour le paiement order=161&erreur=00000&carte=CB&numauto=XXXXXX&numtrans=242106769&numabo=0&montantbanque=3490&sign=Mulb6XU46nv8nCkd0Fp6AO%2BvGWBnWBfOWSYz72Dtr54uelc6M00%2BWMyawj0hNbxD8mcD3FUdlE%2FNPjU1cRXIE2duZPFMLG%2FMr9LjHGDKC1cXmE4WxNWX4wOLHMeMdsFK%2BbP3QG7p0OPfuAbz64XM4LYogqNUhwUSL%2FcyUGxOhpQ%3D (404-0)

La conf : 
Woocommerce est à jour, tt comme la paybox-gateway.

une idée ? merci d'avance !

**Comment by swoelffel** [comment]
Bonjour,
L'Url rewriting est il activé sur votre Apache ?
C'est nécessaire pour le bon fonctionnement : https://codex.wordpress.org/Using_Permalinks
Merci
