### ISSUE TITLE
Impossible to activate plugin

### ISSUE THREAD

**Issue by tototata75** [swoelffel/woocommerce-paybox-gateway#28]
Hello, 

I tried to activate the plugin but it's not possible, I got the following issue (french) :

L’extension n’a pu être activée, car elle a déclenché une erreur fatale.
Le plugin WooCommerce doit être activé pour l'activation de l'extension

Is there a solution ?

Thanks !!

**Comment by swoelffel** [comment]
Hello,
This plugin need WooCommerce plugin to work
Best
