### ISSUE TITLE
Problème de sécurité page de retour Paybox

### ISSUE THREAD

**Issue by thithi242** [swoelffel/woocommerce-paybox-gateway#29]
Bonjour,

J'utilise la version Woocommerce 2.0.20.
J'ai constaté un problème de sécurité sur le module Paybox.

Sur la page de retour de paiement (commande reçue) de Paybox, il existe un problème de sécurité.
Seul le paramètre "order" est nécessaire pour que la page affiche les informations relatives à la commande. Toute personne (authentifié ou non) peut consulter ces informations en changeant le paramètre "order" dans l'URL.

Sur la page de retour de paiement par défaut de Woocommerce (thankyou), il faut obligatoirement le paramètre "order" et le paramètre "key". Ces 2 paramètres sont vérifié avec la ligne suivante (dans le fichier class-wc-shortcode-thankyou) ::
if ( $order->order_key != $order_key )
....

Je pense qu'il y a donc un réel problème de sécurité. Peut-on faire quelque chose pour contourner cela ?

Merci.

**Comment by swoelffel** [comment]
Hello,
Your are right. A patch will be deliver to add order_key check before printing the page.
Thanks
