### ISSUE TITLE
Retour à la boutique > Panier non vidé

### ISSUE THREAD

**Issue by mgauduin** [swoelffel/woocommerce-paybox-gateway#3]
Bonjour,

J'utilise votre plugin avec Woocommerce 2.0.5

Merci beaucoup, celui-ci fonctionne parfaitement puisque le client est bien redirigé vers l'interface Paybox et le montant est bien crédité.

En revanche, au retour sur la boutique, le panier n'est pas vidé et la commande n'est pas signalée comme payée, quel moyen permet d'avoir une solution à ce problème ?

Je précise que l'url de retour que j'ai mis sur la page du plugin correspond à l'url http envoyée à Paybox.

Merci,

MGauduin

**Comment by swoelffel** [comment]
Bonjour,

Avez-vous installé la dernière version du plugin ?
En effet, cette version corrige un problème de compatibilité avec la version 2 de woocommerce traitant justement des retours Paybox.

Merci

**Comment by swoelffel** [comment]
Bonsoir,

Je réponds directement au mail si tu préfères m'envoyer des infos sans passer par github.

Je serais preneur de l'url du site et d'un screenshot des paramètres du plugin pour comprendre le pb (si ce n'est pas un pb de version).

Bonne soirée,

Stéphane

De : mgauduin <notifications@github.com<mailto:notifications@github.com>>
Répondre à : swoelffel/woocommerce-paybox-gateway <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : vendredi 12 avril 2013 19:49
À : swoelffel/woocommerce-paybox-gateway <woocommerce-paybox-gateway@noreply.github.com<mailto:woocommerce-paybox-gateway@noreply.github.com>>
Objet : [woocommerce-paybox-gateway] Retour à la boutique > Panier non vidé (#3)

Bonjour,

J'utilise votre plugin avec Woocommerce 2.0.5

Merci beaucoup, celui-ci fonctionne parfaitement puisque le client est bien redirigé vers l'interface Paybox et le montant est bien crédité.

En revanche, au retour sur la boutique, le panier n'est pas vidé et la commande n'est pas signalée comme payée, quel moyen permet d'avoir une solution à ce problème ?

Je précise que l'url de retour que j'ai mis sur la page du plugin correspond à l'url http envoyée à Paybox.

Merci,

MGauduin

**Comment by mgauduin** [comment]
Bonsoir Stéphane et merci pour cette réponse rapide,

Le site est www.runningoutdoor.fr

J'avais auparavant un problème de liaison serveur, qui s'est aujourd'hui
transformée pour Paybox en erreur 301 (mail que je reçois après la
transaction).

Peux-tu m'envoyer un e-mail à contact@runningoutdoor.fr pour que je
t'envoie directement le fichier class-wc-paybox-gateway.php ?

Merci,

MGauduin

**Comment by swoelffel** [comment]
Bonjour Maxime,
Des news ?
Merci

**Comment by mgauduin** [comment]
Bonjour Stéphane, oui de bonnes nouvelles ça fonctionne mieux. Le panier est bien vidé et la commande enregistrée, le problème était donc bien dû à une mauvaise commande de ma part.

En revanche j'ai toujours une erreur 500 entre le serveur paybox et OVH, les deux se renvoyant la balle...

Merci beaucoup pour le plugin qui est très utile et efficace, ainsi que pour ton aide au dépannage !

A bientôt,

Maxime

**Comment by swoelffel** [comment]
Bonjour,

Si vous utilisez la 2.0.8 pensez à mettre jour le plugin afin de corriger un pb d'enregistrement des paramètres.

Bonne journée.

**Comment by mgauduin** [comment]
Merci pour l'information !

Bonne journée,

Maxime

**Comment by suparub** [comment]
Salutations Messieurs,

quel solution avez vous trouver au probleme? J'ai le meme soucis, utilisant la derniere version du plugin et woocommerce 2.0.10

La commande est bien confirmee sur le site et le paiement effectue mais le panier reste plein et la commande est notee comme "en attente" sur le backoffice.

Url de retour du type:

http://www.monsite.com/commande/commande-cb-recue/?order=3239&erreur=00000&carte=Visa&numauto=724222&numtrans=396065899&numabo=0&montantbanque=100&sign=VKSVTeOJtHGKxaz8gRyE2X6oOmM5gz0I59WTwLP9XetA8b7YQN2DRaIdPrHGyyKA%2F8mBpecrmHgziD%2FU66DhvvA%2BqMz%2FrPi51k%2Fmx07%2BahfMZiett9LUZ0Wd2rpQOOs0lkJMllGXHYfThCACbMwJK34V3P1d%2BHYaygN9uf3rzsg%3D

La config:

Return Link : /commande/commande-cb-recue

 (une page avec le shortcode [im4woo_thankyou] 

Merci d'avance pour une reponse.

**Comment by swoelffel** [comment]
Bonjour,

C'est un problème de configuration de l'autoresponse (à ne pas confondre avec l'URL de retour pour l'internaute).
Manifestement, elle ne doit jamais être rappelée par Paybox et d'après ton commentaire, je pense qu'il y'a une confusion entre la page de retour (avec le shortcode) et l'url d'autoresponse appelée par PB.

Je vais essayer de pousser une mise à jour permettant d'envoyer des informations d'analyse de la configuration depuis l'admin du site.

En attendant, que renvoi l'appel de l'url d'auto-response directement ?

Merci

**Comment by suparub** [comment]
Merci de ta reponse swoellffel

Paybox return URL : /paybox/SignVer.java (si j'ai bien compris)

Me suis-je emmêlé les pinceaux entre l'url du script appelant les fonctions comfirm/cancel/refused et la page de retour?

Signver.java me retourne:

package signver;

import java.security.interfaces.RSAPublicKey;
import java.security.Signature;
import java.security.KeyFactory;
import java.security.spec.X509EncodedKeySpec;
import java.io.FileInputStream;
import java.io.DataInputStream;

import org.apache.commons.codec.binary.Base64;
import org.apache.commons.codec.net.URLCodec;
[...]
      // decodage ...
        byte[] dataBytes = URLCodec.decodeUrl(sData.getBytes());
        byte[] sigBytes = Base64.decodeBase64( URLCodec.decodeUrl(sSig.getBytes()));

```
    // lecture de la cle publique       
    RSAPublicKey pubK = getPubKey("/tmp/pubkey.der");

    // verification signature
    boolean result = verify(dataBytes, sigBytes, "SHA1withRSA", pubK);

    // affichage resultat
    System.out.println("Resultat de la verification de signature : " + result);
}
```

}

**Comment by swoelffel** [comment]
Bonsoir,
Non il y'a un problème la : L'URL en question pointe sur les sources d'une classe Java ?!?
Alors qu'il devrait s'agir d'une URL technique WordPress.
Il faudrait voir avec ton prestataire informatique (ou plutôt un autre).
Si tu as besoin de support, tu peux me contacter sur mon mail : swo(arobas)castelis(point)com
Merci

**Comment by suparub** [comment]
parfait probleme resolu. Merci chef! 

J'ai juste remis la valeure par defaut : /paybox_autoresponse (meme si ca ne pointe nul part). Mon .java etait a coté de la plaque.

(le seul petit soucis now soit que paybox redirige toujours vers la meme page (celle avec le shortcode: /commande/commande-cb-recue) meme lors d'un echec paybox, aka url constamment identique pour "retour a la boutique").  Enfin je chipote la, merci encore !

**Comment by kevdespres** [comment]
Bonjour, 
Tout d'abord merci pour ce plugin très utile :)
J'utilise votre plugin depuis peu et je viens de m'apercevoir que le panier n'est pas vidé et la commande ne change pas de statut dans le cas où le client ne clique pas sur le "retour boutique".
Problème de l'autoresponse sûrement, que dois-je mettre dans ce champs comme url et comme code dans la page ?

**Comment by kevdespres** [comment]
J'ai résolu mon problème en insérant dans le champs "Paybox return URL" l'url de la page qui possède le shortcode [woocommerce_thankyou]. Il serait peut être utile d'en faire mention juste en dessous du champs de la même manière que pour [im4woo_thankyou].

**Comment by swoelffel** [comment]
Bonjour,
C'est en effet un bon contournement du pb.
Je vais toutefois revoir le code de l'URL de retour paybox pour y ajouter celui du woocommerce_thankyou dans le cas ou le retour est positif.
Merci

**Comment by swoelffel** [comment]
Bonjour,
La nouvelle version est sensée corriger le pb sans nécessiter de rajouter le short code woocommerce_thankyou.
Tout retour sera apprécié pour valider le bon fonctionnement.
Merci

**Comment by suparub** [comment]
Parfait ^^ beautiful.

2013/9/6 Stéphane notifications@github.com

> Bonjour,
> La nouvelle version est sensée corriger le pb sans nécessiter de rajouter
> le short code woocommerce_thankyou.
> Tout retour sera apprécié pour valider le bon fonctionnement.
> Merci
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/swoelffel/woocommerce-paybox-gateway/issues/3#issuecomment-23938041
> .

## 

Rubens :°)
