### ISSUE TITLE
Peut-on utiliser le plugin sans payer ?

### ISSUE THREAD

**Issue by davidcouturier** [swoelffel/woocommerce-paybox-gateway#31]
Bonjour,

J'ai installé le plugin Paybox Gateway pour Woocommerce.
Il semble très bien fait et tout fonctionne avec les paramètres donnés pas Paybox ... mais mais mais

Je ne peux pas l'utiliser car je n'ai pas de "customer ID"
You not have a valid cutomer ID : Thanks to buy ticket here before requesting support.

Et pour avoir un "Custumer ID" il faut donc payer au minimum 150€ d'assistance ... un peu cher pour un plugin gratuit à la base. 
Je n'ai pas besoin d'assistance, juste d'un "Custumer ID".

Merci d'avance pour votre réponse claire et rapide.
Sinon je trouverai une autre solution.

Cordialement

**Comment by swoelffel** [comment]
Hello,
Customer ID is required only to request dedicated support.
A customer ID will be given after buying a support ticket.
You can use the plug-in without filling this field.
Stéphane W.
![logo-open-boutique-300x46](https://f.cloud.github.com/assets/3170667/1581212/f39f833c-51d0-11e3-853e-221847ba2267.png)
http://www.openboutique.fr

**Comment by davidcouturier** [comment]
Donc je ne mets pas de Customer ID et ça marchera ?

**Comment by davidcouturier** [comment]
![capture d ecran 2015-04-18 a 14 40 39](https://cloud.githubusercontent.com/assets/12006084/7215563/ef9be17e-e5de-11e4-91d0-31015a96dd84.png)
![capture d ecran 2015-04-18 a 14 40 39](https://cloud.githubusercontent.com/assets/12006084/7215563/ef9be17e-e5de-11e4-91d0-31015a96dd84.png)

**Comment by davidcouturier** [comment]
ca ne semble pas fonctionné meme sans indiqué un customer ID :/
