### ISSUE TITLE
Paiement de test avec votre plugin

### ISSUE THREAD

**Issue by szed** [swoelffel/woocommerce-paybox-gateway#4]
Hello :)
Tout d'abord, merci pour le plugin !

En premier point, un petit bug, avec la dernière version de WooCommerce (2.0.8), les paramétrages ne s'enregistrent pas...j'ai pourtant bien pris le dernier plugin sur github.
Qu'a cela ne tienne, je rentre mes infos en dur dans le code.

Je dois tester un paiement Paybox sur un Kimsufi sur OVH (en sachant qu'il s'agit d'une refonte de site, un ancien Joomla/Virualmart sur 1&1 utilisant déja Paybox. Et le site restera sur 1&1, donc les cgi sont déja prêt et les id aussi.... mais on doit le tester sur notre kimsufi d'abord.)

Donc les cgi sont bien installé et bien trouvé par le plugin. Tout va bien.

Excépté que, pas moyen de tester !
Avec les identifiants/code de test fournis par Paybox ici : http://www1.paybox.com/telechargements/ParametresTestPaybox_V5.08_FR.pdf

J'otbiens apres la redirection vers Paybox : Problème d'identification du commerce.
Accès refusé ! (je tombe sur l'adresse : https://tpeweb.paybox.com/cgi/MYchoix_pagepaiement.cgi) .

Je dois oublier un truc ?

---- ce que j'ai modifié dans le code  
            //$param .= ' PBX_SITE=' . $this->paybox_site_id;
            $param .= ' PBX_SITE=1999888';
            //$param .= ' PBX_IDENTIFIANT=' . $this->paybox_identifiant;
            $param .= ' PBX_IDENTIFIANT=110647233';
            //$param .= ' PBX_RANG=' . $this->paybox_rang;  
            $param .= ' PBX_RANG=32';

et
 //$exe = $this->paybox_exe;
            $exe = '/home/***_myuser**_*/cgi-bin/module_debian64bits_noyau2-6-18_libc2-3-6.cgi';

Du coup le module semble fonctionner, mais tu as peut être déja eu ce cas.
Merci !

Sébastien

Petit Edit !
Alors, j'ai appelé le service technique Paybox, qui m'ont fait remplacer les identifiants de test, par les identifiants réels, mais en rajoutant la ligne :  $param .= ' PBX_PAYBOX=https://preprod-tpeweb.paybox.com/cgi/MYchoix_pagepaiement.cgi'; qui indique que l'on ai en preprod.

Du coup, le paiement s'est bien passé, et je retombe bien sur la boutique.
Par contre, mon panier n'est pas vide, et ma commande n’apparaît pas dans mon historique, ni dans les commandes en BO (de même que je n'ai pas recu de mail concernant ma commande a part une validation du ticket de paiement par paybox).

Tout est normal ? ou pas tout a fait ? :D 

Merci !

**Comment by swoelffel** [comment]
Bonjour,

Le plugin est sensé poster vers l'URL générée par l'exe Paybox. Il me semble que l'URL en question est la bonne.
Il doit manquer un paramètre dans le POST : je regarde ce WE et reviens vers toi.
Le plug in est sensé écrire une ligne dans le php_error.log
Peux-tu stp activer les logs et m'envoyer la ligne en question.

Merci

**Comment by szed** [comment]
Merci pour la  réponse rapide :)
J'ai édité le post, je ne sais pas si tu as vu, j'ai pu effectué un paiment, mais ça rajoute d'autres questions ?

La dernière ligne du log correspondant à l'heure de la commande : 
[Fri Apr 19 11:21:52 2013] [error] [client 82.127.11.161] /home/***_myuser**_*/cgi-bin/module_debian64bits_noyau2-6-18_libc2-3-6.cgi PBX_MODE=4 PBX_OUTPUT=B PBX_SITE=0883994 PBX_IDENTIFIANT=325268870 PBX_R$

**Comment by swoelffel** [comment]
Hello,

Alors, cette ligne correspond a l'exécution de l'exe paybox qui génère le formulaire.
Peux tu stp la copier coller pour l'exécuter en ligne de commande sur ton serveur (après un sudo www-data c'est encore mieux)

Elle devrait te generer un formulaire html (ou un message d'erreur) qui peut m'aider.

Merci

De : szed <notifications@github.com<mailto:notifications@github.com>>
Répondre à : swoelffel/woocommerce-paybox-gateway <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : vendredi 19 avril 2013 11:34
À : swoelffel/woocommerce-paybox-gateway <woocommerce-paybox-gateway@noreply.github.com<mailto:woocommerce-paybox-gateway@noreply.github.com>>
Cc : Stéphane WOELFFEL <swoelffel@castelis.com<mailto:swoelffel@castelis.com>>
Objet : Re: [woocommerce-paybox-gateway] Paiement de test avec votre plugin (#4)

Merci pour la réponse rapide :)
J'ai édité le post, je ne sais pas si tu as vu ?

La dernière ligne du log correspondant à l'heure de la commande :
[Fri Apr 19 11:21:52 2013] [error] [client 82.127.11.161] /home/actmp.pictao.fr/cgi-bin/module_debian64bits_noyau2-6-18_libc2-3-6.cgi PBX_MODE=4 PBX_OUTPUT=B PBX_SITE=0883994 PBX_IDENTIFIANT=325268870 PBX_R$

**Comment by szed** [comment]
Cela me retourne "Content-type: text/html
Cache-Control: no-cache, no-store
Pragma: no-cache

<HTML>
<HEAD>
<TITLE>PAYBOX</TITLE></HEAD>
<BODY>
<CENTER><P><B>PAYBOX INPUT ERROR (code -7)</B></P></CENTER>
<CENTER><B>Version 307 - Sources 5.02</B></CENTER>
<br><CENTER><B>
Linux **_NOTRESERVEUR**_ 3.2.13-xxxx-std-ipv6-64 #1 SMP Wed Mar 28 11:20:17 UTC 20                                     12 x86_64 GNU/Linux
</B></CENTER>
</BODY>
</HTML>
"

Par contre, j'y ai réfléchis, je ne sais pas si la ligne de log que je t'ai envoyé, et que je viens d’exécuter, correspond au paiement que j'ai effectué en préprop avec les identifiants réels (qui lui a marché - cf l'edit de mon 1er post), ou a un des anciens test avec les identifiants de test fournis par paybox (qui eux me renvoient "Problème d'identification du commerce. Accès refusé !" ). J'ai fais les tests a la suite, sans trop faire gaffe à la minute prêt. Et comme le test qui a fonctionné, ne m'a pas enregistré la commande dans WooCommerce, je ne sais plus a quelle heure je l'ai passé.

Séb.

**Comment by szed** [comment]
Hello :)

Avez vous pu jeter un oeil ? 
Je suis inquiet sur le fait que cela ne marche pas une fois en ligne (sous un mutu 1&1), au niveau de la récupération de la commande sur le site après le paiement.

De plus, je suis tomber sur un post sur le forum de WordPress ou la personne avait le problème des champs en back office qui ne s'enregistrait pas. Mais ensuite, elle s'auto répond en disant que c'était ok, que le plugin avait été mis à jour pour woocommerce 2.
Malgrè avoir pris la dernière version sur github, j'ai ce même problème (WP et WooCommerce à jour).
Du coup je me demande si j'ai bien la dernière version...?

Merci :)

**Comment by swoelffel** [comment]
Bonjour,

En effet, il y'avait une incompatibilité avec la 2.0 dans la manière de gérer le hook de sauvegarde.
Je viens de mettre en ligne une nouvelle version qui corrige ce pb.

Je laisse le thread ouvert le temps que vous fassiez vos tests.

Autre point : Je prépare une nouvelle version pour la fin de semaine permettant de parametrer le PBX_PAYBOX depuis l'interface de l'admin ...

Bonne journée.

**Comment by szed** [comment]
Merci :)

Juste une autre question, quelle différence entre "Paybox return URL" qui est à "/paybox_autoresponse" et Return Link qui j'ai mis à "/commande/commande-recue/" ?

**Comment by Struktur** [comment]
On dirait qu'on se pose tous la même question :)
Merci pour la MAJ Stéphane.

**Comment by swoelffel** [comment]
C'est une très bonne question :-)

L'autoresponse est une url "technique" qui permet à Paybox de prévenir le site après le paiement (c'est ce qui entraine le vidage du panier et le changement de statut de la commande)
Le retour est également "logué" sous forme de note dans la commande.

Le return link doit ramener l'utilisateur vers ton site depuis paybox (c'est une vrai page avec le sort [im4woo_thankyou] code qui va bien)

Je peux clôturer le ticket ?

Merci

**Comment by swoelffel** [comment]
@Struktur : En effet,il semblerait que mes explications dans la page d'admin ne soit pas claires.
Ou alors c'est parceque c'est en anglais ?

Si vous avez des idées de modifications de ces commentaires ou souhaitez participer à la localisation en FR, n'hésitez pas à me proposer d'autres "wording"

Merci

**Comment by Struktur** [comment]
Ouvrons un nouveau ticket pour ça pour ne pas polluer celui là ;)

**Comment by swoelffel** [comment]
Ca roule : je clôture le bug et vous pouvez ouvrir un ticket avec des propositions de wording pour l'i18n

**Comment by szed** [comment]
J'arrive un peu après la bataille désolé !
Je sais pas trop ce qui se passe sur github si je répond à une issus cloturé, désolé x)

Par rapport aux URL toujours, et à celle d'autoresponse, si le champ est libre, je suppose qu'elle ne dois pas rester "/paybox_autoresponse". Que doit-elle être du coup ? 

Merci encore :)

**Comment by swoelffel** [comment]
Bonjour,
Tu peux le laisser avec paybox_autoresponse sauf si tu as paramètré autre chose côté paybox.
Sinon, l'URL autoresponse est envoyée avec la requête à Paybox donc Paybox sait ou répondre.

Pour tester le fonctionnement , tu peux appeler l'url : http://www.tonsite.fr/paybox_autoresponse?order&sign

Tu dois avoir une page blanche avec "Test AutoResponse OK"
Je vais travailler à une mise à jour pour que ce lien soit inclus dans ma page paramètre et renvoi des infos de diagnostique sur l'installation
