### ISSUE TITLE
Améliorations / improvements

### ISSUE THREAD

**Issue by Struktur** [swoelffel/woocommerce-paybox-gateway#5]
Pour ma part, je suis partant pour apporter mon aide/suggestion sur le wording.
De même pour l'interface du plugin (création d'un petit header graphique ? Iconographie ? etc...)

I'm ok to help on wording and french translation.
Also, I could help on visual design, create icons, making an eye-catching header that helps introduce the plugin.

**Comment by swoelffel** [comment]
Pour info : un extract des libellés actuels (EN) :

This controls the title which the user sees during checkout.

Let the customer know the payee and where they should be sending the Paybox to and that their order won't be shipping until you receive it.

Please enter you ID Site provided by PayBox.

Please enter you Paybox ID provided by PayBox.

Please enter Paybox Rank provided by PayBox.

Please enter Paybox Key provided by PayBox.

Please enter the autoreponse URL for PayBox.

Please enter back link from PayBox (where you need to put the [im4woo_thankyou] shortcode).

Please enter the posting URL for paybox Form 
For testing : https://preprod-tpeweb.paybox.com/cgi/MYchoix_pagepaiement.cgi
For production : https://tpeweb.paybox.com/cgi/MYchoix_pagepaiement.cgi

Message to the user before redirecting to PayBox.

Location for Paybox executable (http://www1.paybox.com/telechargement_focus.aspx?cat=3).

**Comment by swoelffel** [comment]
Pas de volontaire pour les traductions ?
