### ISSUE TITLE
Message de retour paybox

### ISSUE THREAD

**Issue by ghost** [swoelffel/woocommerce-paybox-gateway#6]
Bonjour,

Tout d'abord je tiens à vous remercier pour ce plugin très utile !
J'ai mis le système paybox sur mon site grâce à votre plugin, seul hic le message de retour est toujours le même que le client est annulé, ou bien réussi le paiement.

Il y'a toujours "merci de votre commande" pourtant quand on annule le paiement je voit bien dans l'url erreur=00001

Je suis quasiment sur que le problème vient de moi car je n'ai pas su remplir "Paybox return URL"

Je tien à préciser qu'il y'a juste le message qui n'est pas bon, le panier est bien vidé en cas de réussite et laisser en cas d’échec !

Merci d'avance !

Ps : la ligne 212 :  $param .= ' PBX_CMD=' . $order->paybox_url;
ce serait pas plutôt $param .= ' PAYBOX=' . $order->paybox_url;

**Comment by swoelffel** [comment]
Bonjour,

Je viens de pousser une nouvelle version utilisant les paramètres PBX_REFUSE et PBX_ANNULE pour renseigner les URLs de retour en cas d'annulation ou d'erreur de transaction.
Il suffit de créer les 2 pages adhoc.
Je n'ai pas l'occasion de tester en live : tout retour sera le bienvenue.

Bonne journée

**Comment by ghost** [comment]
Bonjour,

J'ai tester qu'une seul fois chaque cas (réussi,annule et erreur) et ça fonctionne , Merci !

Bonne journée

**Comment by swoelffel** [comment]
Merci pour le retour.
Concernant la ligne 272, elle n'a rien à faire la -> j'enlève
2 améliorations à venir : ajout d'une 4eme URL pour gérer les retours erreur de paybox (PBX_ERREUR) + Ajour d'un bouton pour poster la configuration vers un page de maintenance chez moi afin de faciliter le debuggage.

A suivre ...
