### ISSUE TITLE
Annulation Paybox

### ISSUE THREAD

**Issue by clmntclmnt** [swoelffel/woocommerce-paybox-gateway#7]
Bonjour,

Tout d'abord merci pour ce plugin qui m'a été d'une grande aide.

J'avais cependant une question, comment gérer les retours sur les annulations et les abandons une fois retourné sur le site?

Merci d'avance de la réponse.

**Comment by swoelffel** [comment]
Bonjour,
Il me semble qu'actuellement un retour sur abandon ou annulation ne vide pas le panier.
Quel est le comportement qui pose problème ?

**Comment by clmntclmnt** [comment]
C'est plus au niveau du statut de la commande que ça bloque. Elle reste en attente. Y a t'il une méthode ou un script pour passer la commande à l'état "Annulée" dans ces cas là?

**Comment by swoelffel** [comment]
Cela ne me parait pas anormal qu'elle reste "en attente" car le client peut ré-utiliser le panier et faire un paiement sans avoir à refaire tout le process (cas d'un changement de carte par ex).
Si je comprends bien, vous souhaiteriez plutôt un traitement "batch" faisant le ménage dans les commandes en attentes au bout d'un certain temps, c'est bien ca ?
Il serait peut-être pertinent d'en profiter pour relancer le client dans le cadre d'un mailing ad hoc en utilisant les paniers non aboutis ... mais ca dépasse le cadre de ce plug-in.
Une idée de développement à creuser tout cas ...
N'hésitez pas à ré-ouvrir le ticket si je n'ai pas compris le pb.
Merci

**Comment by clmntclmnt** [comment]
Ça répond a ma question! Merci beaucoup !

**Comment by clmntclmnt** [comment]
Ok, un nouveau truc que je ne comprends pas.
J'ai cloné la bêta 0.2.4. Celle avec le nouveau shortcode dans la thankyou page.
Peu importe le success ou la failure du paiement, la commande reste à l'état "En attente".
La validation de la commande se fait-elle à la main?

EDIT : Peut être dû à la MAJ 2.0.15 de WC?
