### ISSUE TITLE
Paybox_Autoresponse Code erreur HTTP 500

### ISSUE THREAD

**Issue by ghost** [swoelffel/woocommerce-paybox-gateway#8]
Bonjour, j'ai un problème d'erreur HTTP 500 entre le serveur PAYBOX et OVH.
En effet après paiement, mon serveur renvoie bien la page "Autoresponse". Tout semble fonctionner normalement mais Paybox m'envoie systématiquement un WARNING correspondant cette erreur HTTP 500.

Détails sur mon installation

Wordpress v3.6 sur hébergement OVH
Woocommerce v2.0.13
La dernière version de l'extension WC Paybox Gateway

Mon installation Wordpress/Woocommerce se trouve dans un sous-répertoire du site, du type :

http://www.monsite.com/shop

Dans les paramètres de l'extension WC Paybox Gateway, j'ai indiqué 
- Paybox return URL : /shop/paybox_autoresponse
- Successful Return Link : /shop/commande/paiement-par-carte-bancaire-termine/
  (page contenant le shortcode [im4woo_thankyou])

Voici un exemple d'email reçu de PAYBOX (tpeweb@paybox.com) :

WARNING: Impossible de joindre http://www.monsite.com/shop/paybox_autoresponse pour le paiement order=674&erreur=00000&carte=CB&numauto=XXXXXX&numtrans=206446908&numabo=0&montantbanque=880&sign=h%2Frn3GSkDwpQuTQbbApZQ7hUpMsrdlCVdzUOUWV%2Be0sCBoD4Ffz%2FcaeQ8HHorBBws6c0tunCi2m%2BPv3ZA39HALdyl6q0fyL3mpjqN4C%2Fkrc61x%2BisM4TM2eqkw3dBtKZPmwAhBFSjE9CsSfvafpw8n7SYeftGDNkCM8t90aCKOk%3D 

Ce que je lis dans les logs de mon site Web :

XXX.XXX.XXX.XXX www.monsite.com - [05/Sep/2013:15:59:11 +0200] "GET /shop/paybox_autoresponse?order=674&erreur=00000&carte=CB&numauto=XXXXXX&numtrans=206446908&numabo=0&montantbanque=880&sign=h%2Frn3GSkDwpQuTQbbApZQ7hUpMsrdlCVdzUOUWV%2Be0sCBoD4Ffz%2FcaeQ8HHorBBws6c0tunCi2m%2BPv3ZA39HALdyl6q0fyL3mpjqN4C%2Fkrc61x%2BisM4TM2eqkw3dBtKZPmwAhBFSjE9CsSfvafpw8n7SYeftGDNkCM8t90aCKOk%3D HTTP/1.1" 500 4088 "-" "curl/7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5"

Quand depuis mon navigateur j'appelle l'adresse http://www.monsite.com/shop/paybox_autoresponse?order&sign
le navigateur affiche bien le message : Test AutoResponse OK

Mais dans les logs de mon site Web je lis toujours :

XXX.XXX.XXX.XXX www.monsite.com - [05/Sep/2013:16:04:34 +0200] "GET /shop/paybox_autoresponse?order&sign HTTP/1.1" 500 1488 "-" "Mozilla/5.0 (Windows NT 5.1; rv:23.0) Gecko/20100101 Firefox/23.0"

Une idée de ce qui peut générer ce code HTTP 500 ?

Merci d'avance pour votre aide

**Comment by swoelffel** [comment]
Bonjour,
Les logs d'erreurs PHP (voir php.ini) serait utiles à la compréhension du pb.
Merci

**Comment by ghost** [comment]
Bonjour, Merci pour cette réponse rapide.

Malheureusement, je n'ai pas accès au fichier PHP.INI (hébergement mutualisé chez OVH), donc je ne peux pas activer les logs d'erreur. 

Je ne m'y connais pas trop en débogage PHP et je ne vois pas comment je peux contourner ce problème...

EDIT 

J'ai finalement pu activer les logs php grâce au fichier .USER.INI (PHP v5.3)

Voici ce que j'obtiens dans les logs php quand j'appelle l'adresse http://www.monsite.com/shop/paybox_autoresponse?order&sign

[06-Sep-2013 10:26:32 UTC] PHP Strict Standards:  Declaration of WC_Paybox::process_payment() should be compatible with that of WC_Payment_Gateway::process_payment() in /xxxxxxxxxxx/shop/wp-content/plugins/woocommerce-paybox-gateway-master/class-wc-paybox-gateway.php on line 29

[06-Sep-2013 10:26:33 UTC] PHP Notice:  Undefined property: WC_Paybox::$debug in /xxxxxxxxxxx/shop/wp-content/plugins/woocommerce-paybox-gateway-master/class-wc-paybox-gateway.php on line 44

Je ne pense pas que ce soit lié à mon problème...

EDIT (2)

Je ne comprends pas très bien pourquoi mais le problème est résolu en remplaçant les "wp_die" par "die" dans la fonction woocommerce_paybox_check_response()

Est-ce que vous expliquez cela ?

Cordialement,
Régis

**Comment by ghost** [comment]
Après avoir remplacé les appels "wp_die" par "die" dans la fonction woocommerce_paybox_check_response(), je me suis penché sur la documentation de ces 2 fonctions.

Il s'avère que la fonction wp_die a un argument "response" qui est par défaut 500.
si on l'appelle de cette manière :

wp_die('Test AutoResponse OK', '', array('response' => 200));

La page générée renvoie bien un code HTTP 200
De plus, toujours dans la fonction woocommerce_paybox_check_response(), la ligne header('HTTP/1.1 200 OK'); semble inutile puisque wp_die() renvoie le code header.

Il semble donc que le problème soit résolu en remplaçant tous les appels du type :
header(...)
wp_die(...)

par un appel approprié du type :
wp_die($message, $title, array('response' => $reponse_http));

Cela vous semble-t-il correct ?

Cordialement,
Régis

**Comment by swoelffel** [comment]
Bonjour,

Bien vu !!
Je viens de pousser une nouvelle version qui devrait corriger le problème.

Cordialement,
Stéphane
