### ISSUE TITLE
Le plugin fonctionne t-il avec l'extension "Subscription"?

### ISSUE THREAD

**Issue by Clement-G** [swoelffel/woocommerce-paybox-gateway#9]
Bonjour, 
Mes clients sont au Crédit Agricole et souhaitent vendre des abonnements en ligne. Pour se faire, la seule solution viable proposée par le CA est donc Paybox. J'ai donc installé le plugin, et aujourd'hui lorsque je teste l'achat de produits "classiques" tout semble fonctionner. En revanche, lorsque je tente de payer un produit géré via "Subscription" (plugin d'abonnements: http://www.woothemes.com/products/woocommerce-subscriptions/?utm_source=extension_home_page_banner&utm_medium=banner&utm_campaign=Banners), le plugin ne semble pas pris en charge au niveau du "checkout" (Message: Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements.). 

D'où mes questions:
- Le plugin fonctionne t-il avec l'extension "Subscription" de WooThemes ?
- S'il n'est pas compatible y'a t-il une manière d'arranger ce problème?

Merci d'avance
Clem

**Comment by swoelffel** [comment]
Bonsoir Clément,

Désolé mais je ne connais pas ce pluggin. Il m'est donc difficile de te répondre sur une compatibilité éventuelle.
Si tu penses développer un "addon" sur le sujet, il est le bienvenue sur le projet ;-)

J'ai lancé le développement d'un nouveau plugin pour gérer SoColissimo dans WooCommerce et n'ai pas prévu de développer de nouvelles "features" pour le plugin PayBox à court terme. Je retiens toutefois l'idée des abonnements dans ma backlog.

De manière générale, concernant les abonnements, j'ai déjà mis en oeuvre ce type de fonctionnalité avec Paybox qui a une offre de service très performante mais cela dépasse le cadre de ce plugin.
En effet, la gestion d'abonnement implique la mise en place de traitement batch pour gérer les échéances, les rejets, les changements de cartes ... bref c'est un projet à part entière.

A ta dispo pour en discuter si tu as besoin d'aide sur le sujet.

Bonne soirée,

Stéphane

**Comment by Clement-G** [comment]
Salut Stéphane, 
merci pour ta réponse. "Subscription" est un plugin développé par l'équipe de Woothemes. Il permet aisément de gérer les abonnements avec Woocommerce et marche par défaut avec la passerelle Paypal. 

Comme tu peux l'imaginer, nos clients ont leur propre banque et souhaitent bien évidement passer par elle pour la gestion de leur Business, nous devons donc en passer par là... Malheureusement les plugs Woocommerce / Paybox opensource ou payants ne gèrent pas les abonnements proposés par Paybox ce qui est fort dommage dans notre cas. Nous devons donc trouver une solution... En tout cas si nous développons cette fonctionnalité à partir de ton travail, nous n'hésiteront pas à te poster tout ça. 
Merci pour ta proposition d'aide, je n’hésiterais pas si besoin. 
A bientôt
Clément
